currencies: ['rub', 'usd', 'byn', 'uah']
email_from: 'office@howtohireme.ru'
contacts_email: 'juniorjobs.email@gmail.com'
telegram: 'https://t.me/juniorjobs'
twitter_name: 'https://twitter.com/juniorjobs'
github: 'https://github.com/howtohireme/juniorjobs'

emails_offset: 500

site_url: 'https://juniorjobs.ru'

seo:
  allowed:
    - '/robots.txt'
    - '/about'
    - '/contributors'
    - '/terms'
    - '/contact_us'
    - '/jobs/*'

  description: "JuniorJobs Description"
  keywords: "JuniorJobs Keywords"
