apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user www-data;
    worker_processes 4;
    pid /var/run/nginx.pid;

    events { worker_connections 1024; }

    http {
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      types_hash_max_size 2048;
      server_tokens off;

      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log;

      gzip on;
      gzip_disable "msie6";
      gzip_types text/plain text/xml text/css text/comma-separated-values;

      include /etc/nginx/conf.d/*.conf;

      upstream app_server {
        server juniorjobs:5000 fail_timeout=0;
      }

      server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name juniorjobs.ru www.juniorjobs.ru;

        # NOTICE: Lets serve static by rails for now
        #location ~* ^.+.(ttf|woff|woff2|jpg|jpeg|gif|css|png|js|ico)$ {
          #root /public;
          #gzip_static on;
          #expires max;
          #add_header Cache-Control public;
        #}

        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Host $http_host;
          proxy_pass http://app_server;
        }

        error_page 500 /500.html;
        error_page 404 /404.html;
      }
    }
